"""Trade ledger: record every Kalshi order we actually PLACE (the price we *took*), then
match each take to the realized match result so we can measure live P&L and tune our edges.

This is deliberately separate from `calibration.py`. Calibration logs EVERY quoted price on
every run (the whole board) to fit the one-way devig margin and the UD/365 blend weight across
all props. This logs ONLY the bets we made — so we can answer a different set of questions:

  * Are we actually *winning*? realized P&L, ROI, hit rate.
  * Is our fair well-calibrated on the bets we sized money behind (vs. just quoted)?
  * Which SOURCE drove the take — bet365-anchored (raw hazard x minutes) or the MODEL
    projection — and which one makes money? (the underdog/365 vs model read.)
  * Are our MINUTES and HAZARD assumptions right where it counted? (each take stores the
    minutes it assumed and the raw hazard it priced from, alongside the realized outcome.)

Storage:
  data/trades/fills.jsonl   — one JSON object per placement, append-only, never rewritten
                              (crash-safe: a placed order is recorded the instant it fills).
  data/trades/settled.parquet + out/trades.csv — the resolved view, regenerated by resolve().

`log_fill` is called from the two (and only two) order paths: board.place (the webapp ticket)
and kalshi_orders.approve_and_place (the `run.py --trade` CLI). It must NEVER raise into those
paths — a placed order that fails to log warns loudly but does not undo the trade.
"""
from __future__ import annotations

import json
from datetime import datetime, timezone

import pandas as pd

import config
from normalize import norm_name

# board market label -> the canonical stat the calibration outcome resolver uses
_MARKET_STAT = {"G": "Goals", "A": "Assists", "G+A": "Goals + assists"}

# the columns we surface in the settled CSV (everything else stays in the parquet)
_VIEW_COLS = ["captured_at", "match", "player", "market", "side", "mode", "source",
              "price_c", "count", "fair", "edge_c", "minutes", "hazard",
              "finished", "realized", "hit", "bet_won", "pnl", "roi", "matched"]


# --------------------------------- logging ----------------------------------

def log_fill(*, ticker, match, player, market, side, price_c, count, order_id=None,
             client_order_id=None, mode=None, source=None, fair=None, q_yes=None,
             minutes=None, hazard=None, kickoff=None, post_only=None,
             k_yes_bid=None, k_yes_ask=None, k_no_bid=None, k_no_ask=None,
             captured_at=None) -> bool:
    """Append one placed order to the ledger with its full pricing context. Returns True on
    success. Best-effort: catches and warns on any failure so it can never break a placement
    that already went through on Kalshi.

      fair    -- our fair probability for the SIDE we bought (P this leg settles in the money)
      q_yes   -- our fair YES prob for the MARKET (side-independent: g_p/a_p/ga_p)
      minutes -- the minutes we assumed for the player at take time
      hazard  -- the raw (vigged) bet365 anytime hazard the leg priced from (None for G+A)
      k_*     -- the live Kalshi book at take time (kept for closing-line-value analysis later)
    """
    try:
        price_c, count = int(price_c), int(count)
        risk = round(count * price_c / 100.0, 2)
        payout = round(count * (1 - price_c / 100.0), 2)        # net profit if the leg wins
        if fair is None and q_yes is not None:
            fair = q_yes if side == "yes" else 1 - q_yes
        rec = {
            "schema": 1,
            "captured_at": captured_at or datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
            "order_id": order_id, "client_order_id": client_order_id,
            "ticker": ticker, "match": str(match) if match is not None else None,
            "player": str(player) if player is not None else None,
            "nname": norm_name(player) if player is not None else None,
            "market": market, "side": side, "mode": mode, "source": source,
            "price_c": price_c, "count": count, "risk": risk, "payout": payout,
            "fair": None if fair is None else round(float(fair), 4),
            "edge_c": None if fair is None else round((float(fair) - price_c / 100.0) * 100, 1),
            "q_yes": None if q_yes is None else round(float(q_yes), 4),
            "minutes": None if minutes is None else float(minutes),
            "hazard": None if hazard is None else float(hazard),
            "kickoff": kickoff, "post_only": bool(post_only) if post_only is not None else None,
            "k_yes_bid": k_yes_bid, "k_yes_ask": k_yes_ask,
            "k_no_bid": k_no_bid, "k_no_ask": k_no_ask,
        }
        config.TRADES_LOG.parent.mkdir(parents=True, exist_ok=True)
        with open(config.TRADES_LOG, "a", encoding="utf-8") as fh:
            fh.write(json.dumps(rec) + "\n")
        return True
    except Exception as e:                                       # never break a placement
        print(f"  trades: WARNING could not log fill ({e}) -- order placed but UNLOGGED: "
              f"{ticker} {side} {price_c}c x{count}")
        return False


def load_fills() -> pd.DataFrame:
    """Every logged take as a DataFrame (one row per placement). Empty frame if none yet."""
    path = config.TRADES_LOG
    if not path.exists():
        return pd.DataFrame()
    rows = []
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            rows.append(json.loads(line))
        except ValueError:
            continue                                             # skip a half-written line
    return pd.DataFrame(rows)


# ------------------------------ resolution + P&L -----------------------------

def resolve(fills=None) -> pd.DataFrame:
    """Match every logged take to its realized result and compute P&L. Reuses calibration's
    API-Football outcome resolver (same data source as the rest of the pipeline), so a take is
    settled once its fixture is FINISHED — a benched player simply resolves to 0 (no goal/assist).

    Per take:
      hit       -- did the market come in? (Goals/Assists/G+A realized >= 1; the line is 0.5)
      bet_won   -- hit if we bought YES, else not hit
      pnl       -- +count*(1-price) if won, -count*price if lost   (dollars)
      matched   -- was the player found in that finished fixture's box score? (False => DNP
                   OR a name-seam miss; a False with bet_won loss is worth eyeballing)

    Writes settled.parquet + out/trades.csv and returns the settled frame (pending takes,
    whose fixture has not finished, are excluded from the settled view)."""
    import calibration                                           # lazy: only when resolving
    from scorers import _names_compatible_loose                   # same seam matcher the board uses

    fills = load_fills() if fills is None else fills
    if fills is None or not len(fills):
        return pd.DataFrame()

    # candidate dates: the kickoff day (else the capture day) and the day after, to be safe.
    ts = pd.to_datetime(fills.get("kickoff"), unit="s", errors="coerce", utc=True)
    cap = pd.to_datetime(fills["captured_at"].astype(str), errors="coerce", utc=True)
    days = ts.fillna(cap).dropna()
    dates = sorted({d.strftime("%Y-%m-%d") for d in days} |
                   {(d + pd.Timedelta(days=1)).strftime("%Y-%m-%d") for d in days})
    outcomes = calibration.resolve_outcomes(dates=dates)

    # per-fixture box score: finished mkeys, realized[(mkey,nname,stat)], and the players who
    # appeared (minutes>0) so we can resolve a take to its OWN fixture and flag DNP/seam misses.
    finished, realized_map, players_by_mkey = set(), {}, {}
    if outcomes is not None and len(outcomes):
        o = outcomes.copy()
        o["mkey"] = o["match"].map(calibration._mkey)
        for _, r in o.dropna(subset=["mkey"]).iterrows():
            finished.add(r["mkey"])
            realized_map[(r["mkey"], r["nname"], r["stat"])] = r["realized"]
            players_by_mkey.setdefault(r["mkey"], set()).add(r["nname"])

    def _lookup(mkey, nname, stat):
        """(realized, matched): exact nname join, else a UNIQUE loose seam match within the
        fixture (mononym/accent variants). Ambiguous or absent => (0, False) — i.e. treated as
        DNP and flagged for eyeballing, never guessed across two players."""
        if (mkey, nname, stat) in realized_map:
            return realized_map[(mkey, nname, stat)], True
        cands = [p for p in players_by_mkey.get(mkey, ()) if _names_compatible_loose(nname, p)]
        if len(cands) == 1:
            return realized_map.get((mkey, cands[0], stat), 0.0), True
        return 0.0, False                                        # DNP or unresolved seam

    out = []
    for _, f in fills.iterrows():
        rec = f.to_dict()
        mkey = calibration._mkey(rec.get("match"))
        stat = _MARKET_STAT.get(rec.get("market"))
        rec["mkey"], rec["stat"] = mkey, stat
        is_done = mkey in finished
        rec["finished"] = bool(is_done)
        if not is_done or stat is None:
            rec.update(realized=None, hit=None, bet_won=None, pnl=None, roi=None, matched=None)
            out.append(rec)
            continue
        realized, matched = _lookup(mkey, rec.get("nname"), stat)
        hit = realized >= 1
        won = hit if rec.get("side") == "yes" else not hit
        price = rec["price_c"] / 100.0
        pnl = round(rec["count"] * (1 - price), 2) if won else round(-rec["count"] * price, 2)
        rec.update(realized=float(realized), hit=bool(hit), bet_won=bool(won), pnl=pnl,
                   roi=round(pnl / rec["risk"], 4) if rec.get("risk") else None,
                   matched=bool(matched))
        out.append(rec)

    df = pd.DataFrame(out)
    settled = df[df["finished"]].copy()
    config.TRADES_SETTLED.parent.mkdir(parents=True, exist_ok=True)
    if len(settled):
        settled.to_parquet(config.TRADES_SETTLED, index=False)
        cols = [c for c in _VIEW_COLS if c in settled.columns]
        config.TRADES_CSV.parent.mkdir(parents=True, exist_ok=True)
        settled[cols].to_csv(config.TRADES_CSV, index=False)
    return settled


# ---------------------------------- summary ----------------------------------

def _grp_pnl(df, col):
    """{group: (n, risk$, pnl$, roi, win_rate)} aggregated over a column."""
    out = {}
    for k, g in df.groupby(col):
        risk, pnl = g["risk"].sum(), g["pnl"].sum()
        out[str(k)] = (int(len(g)), round(float(risk), 2), round(float(pnl), 2),
                       round(float(pnl / risk), 3) if risk else None,
                       round(float(g["bet_won"].mean()), 3))
    return out


def summary(settled=None) -> dict:
    """Headline P&L + breakdowns by source / market / mode, and a coarse calibration of our
    fair vs realized win rate on the bets we actually took. Returns a dict (also printable)."""
    settled = resolve() if settled is None else settled
    if settled is None or not len(settled):
        return {"n_settled": 0}
    s = settled.dropna(subset=["pnl"]).copy()
    if not len(s):
        return {"n_settled": 0}
    risk, pnl = float(s["risk"].sum()), float(s["pnl"].sum())
    res = {
        "n_settled": int(len(s)),
        "total_risk": round(risk, 2), "total_pnl": round(pnl, 2),
        "roi": round(pnl / risk, 3) if risk else None,
        "win_rate": round(float(s["bet_won"].mean()), 3),
        "by_source": _grp_pnl(s, "source"),
        "by_market": _grp_pnl(s, "market"),
        "by_mode": _grp_pnl(s, "mode"),
        # calibration of OUR fair on bets taken: mean fair (P side wins) vs realized win rate.
        "fair_calibration": {"mean_fair": round(float(s["fair"].mean()), 3),
                             "realized_win_rate": round(float(s["bet_won"].mean()), 3),
                             "n": int(s["fair"].notna().sum())},
    }
    unmatched = s[(s["matched"] == False) & (s["bet_won"] == False)]    # noqa: E712
    if len(unmatched):
        res["check_unmatched_losses"] = int(len(unmatched))            # possible name-seam misses
    return res


def _print_summary(summ):
    if not summ.get("n_settled"):
        print("No settled takes yet (place orders, then re-run after the matches finish).")
        return
    print(f"\n===== TRADE LEDGER ({summ['n_settled']} settled) =====")
    print(f"  risk ${summ['total_risk']:.2f}  |  P&L ${summ['total_pnl']:+.2f}  |  "
          f"ROI {summ['roi']:+.1%}  |  win rate {summ['win_rate']:.1%}")
    for label, key in (("by source", "by_source"), ("by market", "by_market"),
                       ("by mode", "by_mode")):
        print(f"\n  {label}:")
        for k, (n, rk, pl, roi, wr) in summ[key].items():
            roi_s = f"{roi:+.1%}" if roi is not None else "  n/a"
            print(f"    {k:10} n={n:3}  risk ${rk:7.2f}  P&L ${pl:+8.2f}  "
                  f"ROI {roi_s:>7}  win {wr:.0%}")
    fc = summ["fair_calibration"]
    print(f"\n  fair calibration (n={fc['n']}): we said {fc['mean_fair']:.1%} avg, "
          f"realized {fc['realized_win_rate']:.1%} won")
    if summ.get("check_unmatched_losses"):
        print(f"\n  NOTE: {summ['check_unmatched_losses']} losing take(s) had no box-score match "
              f"(DNP or a name-seam miss) -- eyeball them in {config.TRADES_CSV}")


if __name__ == "__main__":
    import argparse
    ap = argparse.ArgumentParser(description="Trade ledger: resolve placed takes to results.")
    ap.add_argument("--no-resolve", action="store_true",
                    help="just dump the logged takes, don't hit API-Football for outcomes")
    args = ap.parse_args()

    fills = load_fills()
    print(f"Logged takes: {len(fills)}")
    if not len(fills):
        raise SystemExit(0)
    if args.no_resolve:
        cols = [c for c in ["captured_at", "match", "player", "market", "side", "mode",
                            "source", "price_c", "count", "fair", "edge_c"] if c in fills.columns]
        print(fills[cols].to_string(index=False))
        raise SystemExit(0)
    settled = resolve(fills)
    pending = len(fills) - len(settled)
    if pending:
        print(f"Pending (fixture not finished): {pending}")
    _print_summary(summary(settled))
    if len(settled):
        print(f"\nSettled view written to {config.TRADES_CSV}")
